FROM node:20.13.1

# copy base files
COPY package*.json /usr/src/
COPY yarn.lock /usr/src/
COPY tsconfig.json /usr/src/
COPY .eslintrc.json /usr/src/

# prepare client and copy files
RUN mkdir -p /usr/src/client
WORKDIR /usr/src/client
COPY client/. /usr/src/client/

RUN yarn install

EXPOSE 3000

CMD [ "yarn", "start" ]
