version: '3'

services:
  redis:
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile.dev
    ports:
      - "3001:3001"
    depends_on:
      - redis
    volumes:
      - ./server/src:/usr/src/server/src:ro
  
  client:
    build:
      context: ./
      dockerfile: ./client/Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client/src:/usr/src/client/src:ro

volumes:
  redis_data:
