version: '3'

services:
  redis:
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - redis
  
  # client:
  #   build:
  #     context: ./client
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - server

volumes:
  redis_data:
